### PR TITLE
Add support for boolean-type image conversion

### PR DESCRIPTION
**Pull request by gselzer**
This will ensure that we can convert NumPy arrays of boolean type.

Will not pass until pom-scijava 34 is released.

### CODE REVIEW

**Comment by gselzer** [comment]
We'll also have to bumpy the imglyb version!

**Comment by ctrueden** [comment]
@gselzer I massaged this branch to have the right released versions. But the new test still fails, unfortunately.

**Comment by gselzer** [comment]
@ctrueden yup, it still fails because we need ImageJ/pyimagej#252

**Comment by ctrueden** [comment]
@gselzer Please rebase this branch over the latest main, and mark it as not a draft anymore, assuming it is ready.

**Pull request merged**
