### PR TITLE
Surface <-> Mesh Conversions

### PR DESCRIPTION
**Pull request by gselzer**
This PR adds support for conversion between napari's `Surface` layer type and ImageJ's `Mesh` data type.

### CODE REVIEW

**Comment by gselzer** [comment]
My only concern at this point is how normals are handled. `Mesh`es have normals for each `Vertex` and `Triangle`.

 @tlambert03 do you happen to know if there is some way for me to pass this data to the `Surface` layer? I see that there is a `normals` parameter that represents the normals, but can you actually pass the numerical values of the normals?

My only concern would be that somehow any given normal `n` would become `-n` during the conversion.  Do you have any intuition on this @ctrueden?

**Comment by tlambert03** [comment]
> @tlambert03 do you happen to know if there is some way for me to pass this data to the Surface layer? 

@brisvag or @alisterburt would know better than me

**Comment by ctrueden** [comment]
@gselzer Normals are often programmatically computed, so you may be able to just ignore the problem for now, and see how things go. And augment the conversion as needed later.

**Comment by brisvag** [comment]
Not sure how `normals` work here, but in `vispy` normals are only computed, not provided. They are not held as a piece of data anywhere in napari; instead, they are generated by [this visual](https://github.com/vispy/vispy/blob/main/vispy/visuals/mesh_normals.py). I don't remember if they use a right-handed or left-handed system, but I know they *do* follow one, so if you want your normal to be reversed, simply change the order of the vertices defining that face.

**Comment by gselzer** [comment]
@ctrueden said:

> @gselzer Normals are often programmatically computed, so you may be able to just ignore the problem for now, and see how things go. And augment the conversion as needed later.

Yeah, that's how I was doing it in my tests. I suppose we can just wait until we know it doesn't work?

@brisvag said:

> Not sure how `normals` work here, but in `vispy` normals are only computed, not provided. They are not held as a piece of data anywhere in napari; instead, they are generated by [this visual](https://github.com/vispy/vispy/blob/main/vispy/visuals/mesh_normals.py). I don't remember if they use a right-handed or left-handed system, but I know they _do_ follow one, so if you want your normal to be reversed, simply change the order of the vertices defining that face.

Thanks for the speedy reply! I think I will just hope that the normals are correctly preserved during the transformation. All I am doing is making a copy of the vertices and triangles (side note, should we instead make some wrappers for the `Mesh` type for speed @ctrueden? Might make an issue about this) so I'd think that we are fine so long as ImageJ2 and vispy follow the same system.

**Pull request merged**
