### PR TITLE
Rewrite ImageJ Napari Plugin as an npe2 widget, with a single Search Bar plugin

### PR DESCRIPTION
**Pull request by gselzer**
This PR rewrites the napari-imagej plugin as an npe2 plugin. Ditching the plan to create submenus, this plugin discovers modules using a single searchbar. 

image

When a module is highlighted, `SearchAction`s are generated for that module, displayed at the bottom of the plugin widget. The `Run` action is the only action that differs from the actions' functionalities in Fiji.

image

By running any module, another widget appears to collect parameters from the user. This widget is made using [`magicgui`](https://github.com/napari/magicgui).

image

Once the user presses `run`, the plugin will run the module and then either:
* Add the result as a layer in napari, if the result can be coerced into a layer
* Spawn a new widget with the result,  if the result cannot be coerced into a layer. A checkbox provides the user the ability to spawn the widget in napari or in a new window.

image

### CODE REVIEW

**Comment by gselzer** [comment]
If we pursue this structure, we would close #2

**Comment by ctrueden** [comment]
@gselzer At this point, this branch is strictly better than what's on the main branch, right? So I'm :+1: for merging it ASAP whenever you are ready.

**Comment by gselzer** [comment]
It's *nearly* ready. I'll ping you when it is.

I have no tests written, although I'm not really sure how we can test this

**Comment by gselzer** [comment]
Alright @ctrueden, I have some tests written, but running them unfortunately produces a segfault :slightly_frowning_face:

It has something to do with the JVM shutdown; this was never thrown during my informal testing in napari:

```
(napari-imagej) : gselzer@gselzer-OptiPlex-5090 ~/code/imagej/napari-imagej (npe2) [napari-imagej] »
pytest                                                                                                                                                                                                                                                 #  0 {2022-01-25 13:40:49}
============================================================================================================================== test session starts ===============================================================================================================================
platform linux -- Python 3.10.2, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
PyQt5 5.12.3 -- Qt runtime 5.12.9 -- Qt compiled 5.12.9
rootdir: /home/gselzer/code/imagej/napari-imagej
plugins: napari-0.4.13, qt-4.0.2, napari-plugin-engine-0.2.0
collected 4 items                                                                                                                                                                                                                                                                

src/napari_imagej/_tests/test_function.py ....                                                                                                                                                                                                                             [100%]

================================================================================================================================ warnings summary ================================================================================================================================
../../../miniconda3/envs/napari-imagej/lib/python3.10/site-packages/numpy/distutils/ccompiler.py:17
  /home/gselzer/miniconda3/envs/napari-imagej/lib/python3.10/site-packages/numpy/distutils/ccompiler.py:17: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
    from distutils.sysconfig import customize_compiler

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================================================================== 4 passed, 1 warning in 6.49s ==========================================================================================================================
Fatal Python error: Segmentation fault

Thread 0x00007f2b8bb47740 (most recent call first):
  File "/home/gselzer/miniconda3/envs/napari-imagej/lib/python3.10/site-packages/jpype/_core.py", line 340 in shutdownJVM
  File "/home/gselzer/miniconda3/envs/napari-imagej/lib/python3.10/site-packages/scyjava/__init__.py", line 112 in shutdown_jvm

Extension modules: yaml._yaml, cytoolz.utils, cytoolz.itertoolz, cytoolz.functoolz, cytoolz.dicttoolz, cytoolz.recipes, psutil._psutil_linux, psutil._psutil_posix, markupsafe._speedups, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, scipy._lib._ccallback_c, scipy.sparse._sparsetools, scipy.sparse._csparsetools, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy._lib._uarray._uarray, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special.specfun, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg._flinalg, scipy.linalg._solve_toeplitz, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg.cython_lapack, scipy.linalg._decomp_update, scipy.special._comb, scipy.special._ellip_harm_2, scipy.fftpack.convolve, pydantic.typing, pydantic.errors, pydantic.version, pydantic.utils, pydantic.class_validators, pydantic.color, pydantic.datetime_parse, pydantic.validators, pydantic.networks, pydantic.types, pydantic.json, pydantic.error_wrappers, pydantic.fields, pydantic.config, pydantic.parse, pydantic.schema, pydantic.main, pydantic.dataclasses, pydantic.annotated_types, pydantic.decorator, pydantic.env_settings, pydantic.tools, pydantic, sip, PyQt5.sip, PyQt5.QtCore, PyQt5.QtGui, PyQt5.QtWidgets, PyQt5.QtTest, scipy.spatial.ckdtree, scipy._lib.messagestream, scipy.spatial.qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.spatial.transform.rotation, scipy.ndimage._nd_image, _ni_label, scipy.ndimage._ni_label, scipy.optimize.minpack2, scipy.sparse.linalg.isolve._iterative, scipy.sparse.linalg.dsolve._superlu, scipy.sparse.linalg.eigen.arpack._arpack, scipy.optimize._group_columns, scipy.optimize._trlib._trlib, numpy.linalg.lapack_lite, scipy.optimize._lbfgsb, scipy.optimize.moduleTNC, scipy.optimize._cobyla, scipy.optimize._slsqp, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy.optimize.__nnls, scipy.optimize._highs.cython.src._highs_wrapper, scipy.optimize._highs._highs_wrapper, scipy.optimize._highs.cython.src._highs_constants, scipy.optimize._highs._highs_constants, scipy.linalg._interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap_module, scipy.integrate._odepack, scipy.integrate._quadpack, scipy.integrate.vode, scipy.integrate._dop, scipy.integrate.lsoda, scipy.interpolate._fitpack, scipy.interpolate.dfitpack, scipy.interpolate._bspl, scipy.interpolate._ppoly, scipy.interpolate.interpnd, scipy.interpolate._rbfinterp_pythran, scipy.special.cython_special, scipy.stats._stats, beta_ufunc, scipy.stats._boost.beta_ufunc, binom_ufunc, scipy.stats._boost.binom_ufunc, nbinom_ufunc, scipy.stats._boost.nbinom_ufunc, scipy.stats.biasedurn, scipy.stats.statlib, scipy.stats.mvn, scipy.stats._sobol, scipy.stats._qmc_cy, psygnal._signal, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.strptime, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.tslib, pandas._libs.lib, pandas._libs.hashing, pandas._libs.ops, pandas._libs.arrays, pandas._libs.index, pandas._libs.join, pandas._libs.sparse, pandas._libs.reduction, pandas._libs.indexing, pandas._libs.internals, pandas._libs.writers, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.testing, pandas._libs.parsers, pandas._libs.json, vispy.visuals.text._sdf_cpu, _jpype, matplotlib._c_internal_utils, PIL._imaging, matplotlib._path, kiwisolver, matplotlib._image, tornado.speedups, msgpack._cmsgpack, scipy.io.matlab.mio_utils, scipy.io.matlab.streams, scipy.io.matlab.mio5_utils, numcodecs.compat_ext, numcodecs.blosc, numcodecs.zstd, numcodecs.lz4, numcodecs._shuffle, numcodecs.vlen, imagecodecs._shared, imagecodecs._imcd, PyQt5.QtSvg, PyQt5.QtOpenGL (total: 196)
[1]    50388 segmentation fault (core dumped)  pytest
```

**Comment by gselzer** [comment]
After some more debugging, I am of the opinion that I am being bitten by the same bug @hinerm was dealing with [here](https://github.com/imagej/pyimagej/commit/57f4b3ec49021386d2db6fa848b35831624b7d02#diff-0e2c397ec9dd448eaa68ff7a3a6081b51bf6799ae4202a2acc0670332c7942fe). By adding `-p no:faulthandler` to my CLI `pytest` call, I did not receive a single segfault in 10 pytest calls (where I had seen it about half the time before).

**Pull request merged**
