### PR TITLE
Change button name from Run to Initialize

### PR DESCRIPTION
**Pull request by gselzer**
This PR aims to close https://github.com/imagej/napari-imagej/issues/48

### CODE REVIEW

**Comment by ctrueden** [comment]
How hard would it be to make it populate a pane below the search results whenever you select an item on the list? So you don't even need to click a button?

**Comment by gselzer** [comment]
> How hard would it be to make it populate a pane below the search results whenever you select an item on the list? So you don't even need to click a button?

Not terribly difficult, we just need to add a callback for the a particular widget event.

I prefer @hinerm's suggestions in #55, though.

**Comment by ctrueden** [comment]
> I prefer @hinerm's suggestions in https://github.com/imagej/napari-imagej/issues/55, though.

How are #55 and my suggestion related? The former is about more responsive feedback for long-running plugins, while this PR is about making the "Run" button less confusingly named. My suggestion would be a way to consolidate things so that you don't have to click a button after selecting a plugin, but rather can immediately start filling in input values to the pane that magically appeared, or even just press enter to execute it immediately with last-used values.

**Comment by gselzer** [comment]
> > I prefer @hinerm's suggestions in https://github.com/imagej/napari-imagej/issues/55, though.
> 
> How are #55 and my suggestion related? 

Oh, I'm sorry, I linked the wrong issue.

I meant #53

**Comment by gselzer** [comment]
@ctrueden I'm going to merge this. Please feel free to either file a new issue or append #53 with any ideas for improvement.

**Pull request merged**
