### PR TITLE
Use str instead of PyImageJ Conversion Framework when creating SearchResultItems

### PR DESCRIPTION
**Pull request by gselzer**
It's much faster, which is important when we could be making thousands of these things.

@hinerm can you confirm that this is much faster for you?

### CODE REVIEW

**Comment by hinerm** [comment]
> @hinerm can you confirm that this is much faster for you?

For me it was about 20% faster than the `main` branch (8 seconds vs. 10 seconds to search for 'a'). So, it seems better but maybe not sufficient.

What kind of speedup were you seeing on your system?

**Comment by gselzer** [comment]
> > @hinerm can you confirm that this is much faster for you?
> 
> For me it was about 20% faster than the `main` branch (8 seconds vs. 10 seconds to search for 'a'). So, it seems better but maybe not sufficient.
> 
> What kind of speedup were you seeing on your system?

I'm seeing a little under 2 seconds with this change vs. about 7 seconds without it.

**Comment by hinerm** [comment]
I did some local testing and then realized that I did something dumb when I was checking out the branch to review. Your change works great @gselzer!

**Review by hinerm — APPROVED** [review]
Significantly speeds things up for me!

**Pull request merged**
